app = "terenbot"
primary_region = "cdg"

[build]

[http_service]
  internal_port = 3002
  force_https = true
  auto_stop_machines = false   # не давать засыпать
  auto_start_machines = true
  min_machines_running = 1     # всегда хотя бы 1 машина
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
